name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'init'
        tf_actions_version: 0.14.3

    - name: Terraform Destroy
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'destroy'
        tf_actions_version: 0.14.3
        args: '-auto-approve'
